name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Client-specific steps
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
        
      - name: Run tests
        working-directory: ./client
        run: npm test -- --coverage --watchAll=false
        
      - name: Build production app
        working-directory: ./client
        # Ignore all warnings, so it deploys
        run: CI=false DISABLE_ESLINT_PLUGIN=true npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_FIREBASE_APP_ID: ${{secrets.REACT_APP_FIREBASE_APP_ID}}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.REACT_APP_FIREBASE_MEASUREMENT_ID}}
          REACT_APP_SIGNALING_SERVER_URL: ${{ secrets.REACT_APP_SIGNALING_SERVER_URL }}
   
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBNOTE_DF968 }}
          channelId: live
          projectId: webnote-df968